server:
  port: 9090
  #配置rabbitMQ服务器

mybatis-plus:
  type-aliases-package: com.wangshili.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列（Queue）
    publisher-returns: true

  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8&useAffectedRows=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.wangshili.dao:
      debug
